# Generated by Django 2.2.12 on 2021-05-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20210513_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
